# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_employee_job_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hierarchy.Entity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Entity')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='jobemployee',
            field=models.ManyToManyField(blank=True, null=True, to='hierarchy.Employee'),
        ),
    ]
