# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportType',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hierarchy.Entity'),
        ),
    ]
