# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.DateTimeField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('work', models.TextField(blank=True, max_length=5000)),
                ('awards', models.TextField(blank=True, max_length=5000)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('popularity', models.SmallIntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
