# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.TimeField(default='09:35'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.TimeField(default='08:40'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
        ),
    ]
