# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Ongoing')], default=2),
        ),
    ]
