# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Abandoned'), (2, 'Completed'), (3, 'Ongoing')], default=3),
        ),
    ]
