# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170318_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submitrequest',
            field=models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=2),
        ),
    ]
