# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_part_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='difficulty',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ManyToManyField(to='job.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Supervisor')], default=1),
        ),
    ]
