# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170401_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='job.User'),
        ),
    ]
