# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_joblevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobLevel',
        ),
        migrations.AddField(
            model_name='job',
            name='joblevel',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Supervisor')], default=1),
        ),
    ]
