# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
