# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20170401_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reportType', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=2)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.IntegerField(choices=[(1, 'Absent'), (2, 'Present')], default=2),
        ),
        migrations.AddField(
            model_name='report',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='job.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.User'),
        ),
    ]
